tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "fd"
brew "jq"
brew "mas"
brew "neofetch"
brew "neovim"
brew "id3v2"
brew "wget"
brew "bluesnooze"
brew "yt-dlp"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
cask "monitorcontrol"
cask "mimestream"
cask "adobe-creative-cloud"
cask "alfred"
cask "alt-tab"
cask "hiddenbar"
cask "coconutbattery"
cask "eloston-chromium"
cask "iina"
cask "iterm2"
cask "keepingyouawake"
cask "openinterminal"
cask "rectangle"
cask "rocket"
cask "sf-symbols"
cask "secretive"
cask "signal"
cask "scroll-reverser"
cask "spotify"
cask "suspicious-package"
cask "veracrypt"
cask "visual-studio-code"
mas "Keynote", id: 409183694
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
