#! /bin/bash
#
# Source: https://raw.githubusercontent.com/orrsella/dotfiles/master/links
#
# List of files/folders to be symlinked.
#
# Symlink will be created from source (in dotfiles repo) to destination
# (existing file to override).
# - **Make sure** to leave an empty line at the end of the list
# - Escape white spaces with \
# - Line format: destination, source
#   desination - The original file on disk
#   source -     The symlinked file in the dotfiles repo folder structure,
#                relative to the repo's base dir

# Example:
# ~/.bash_profile, /bash/.bash_profile
# ~/.test, /dir12/.test

# Zsh
~/.zshrc, /zsh/zshrc

# Git
~/.git/.gitignore, /git/gitignore

# Vim
~/.vim, /vim

# coconutBattery
~/Library/LaunchAgents/com.coconut-flavour.coconutBattery-Menu.plist,/coconutBattery/LaunchAgent.plist

# iTerm2
~/Library/Application\Support/iTerm2/DynamicProfiles/fix-iterm2-keys-profile.json,/iterm2/dynamicProfiles/fix-iterm2-keys-profile.json

